openapi: 3.0.1
info:
  title: '@project.name@'
  description: '@project.description@'
  termsOfService: http://sedia.com/
  version: '@project.version@'
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /v1/gaen/exposed:
    post:
      tags:
      - gaen-controller
      operationId: addExposed
      parameters:
      - name: User-Agent
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gaenRequest:
                  $ref: '#/components/schemas/GaenRequest'
                principal:
                  type: object
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /v1/gaen/exposed/{keyDate}:
    get:
      tags:
      - gaen-controller
      operationId: getExposedKeys
      parameters:
      - name: keyDate
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: publishedafter
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/zip:
              schema:
                type: array
                items:
                  type: string
                  format: byte
  /v1/gaen/exposednextday:
    post:
      tags:
      - gaen-controller
      operationId: addExposedSecond
      parameters:
      - name: User-Agent
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gaenSecondDay:
                  $ref: '#/components/schemas/GaenSecondDay'
                principal:
                  type: object
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /v1/gaen/exposedjson/{keyDate}:
    get:
      tags:
      - gaen-controller
      operationId: getExposedKeysAsJson
      parameters:
      - name: keyDate
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: publishedafter
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GaenExposedJson'
  /v1/gaen/buckets/{dayDateStr}:
    get:
      tags:
      - gaen-controller
      operationId: getBuckets
      parameters:
      - name: dayDateStr
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DayBuckets'
components:
  schemas:
    GaenKey:
      required:
      - keyData
      - rollingPeriod
      - rollingStartNumber
      - transmissionRiskLevel
      type: object
      properties:
        keyData:
          maxLength: 24
          minLength: 24
          type: string
        rollingStartNumber:
          type: integer
          format: int32
        rollingPeriod:
          type: integer
          format: int32
        transmissionRiskLevel:
          type: integer
          format: int32
        fake:
          type: integer
          format: int32
    GaenRequest:
      required:
      - delayedKeyDate
      - gaenKeys
      type: object
      properties:
        gaenKeys:
          maxItems: 14
          minItems: 14
          type: array
          items:
            $ref: '#/components/schemas/GaenKey'
        delayedKeyDate:
          type: integer
          format: int32
    GaenSecondDay:
      required:
      - delayedKey
      type: object
      properties:
        delayedKey:
          $ref: '#/components/schemas/GaenKey'
        fake:
          type: integer
          format: int32
    GaenExposedJson:
      required:
      - gaenKeys
      type: object
      properties:
        gaenKeys:
          type: array
          items:
            $ref: '#/components/schemas/GaenKey'
        header:
          $ref: '#/components/schemas/Header'
    Header:
      type: object
      properties:
        startTimestamp:
          type: integer
          format: int64
        endTimestamp:
          type: integer
          format: int64
        region:
          type: string
        batchNum:
          type: integer
          format: int32
        batchSize:
          type: integer
          format: int32
    DayBuckets:
      type: object
      properties:
        dayTimestamp:
          type: integer
          format: int64
        day:
          type: string
        relativeUrls:
          type: array
          items:
            type: string
